language: node_js
cache: yarn
node_js:
  - node
  - "8"
  - "6"
  - "4"
before_install:
  - npm install grunt-cli -g
  - npm install npm@latest -g
install:
  - YARN_IGNORE_ENGINES=true yarn
  - npm ci
